language: python
python:
  - "2.7"

addons:
  firefox: latest-esr
  apt:
    packages:
    - apache2
    - curl
    - muscle 
    - python-dev
    - python-virtualenv 
    - wget
    - xvfb

cache:
  directories:
  - venv
  - superphy/database
  - blast

before_cache:

before_install:

install:
 - python setup.py install

# command to run tests
script:
 - python setup.py test