env:
  global:
    - SUPERPHY_CONFIGFILE="$TRAVIS_BUILD_DIR/tests/travis-settings.cfg

language: python

python:
  - "2.7"

addons:
  firefox: "41.0"
  apt:
    packages:
    - libyajl1

install:
  - virtualenv --no-site-packages venv
  - echo "source $TRAVIS_BUILD_DIR/bash/postactivate.sh" >> venv/bin/activate
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install -r venv/requirements.txt
  - nodeenv -p --prebuilt --requirements=venv/npm-requirements.txt

# command to run tests
script: xvfb-run -a nosetests && cd tests && xvfb-run -a jasmine-ci && cd ../