language: python

python:
  - "2.7"

addons:
  firefox: "41.0"
  apt:
    packages:
    - libyajl1

cache:
  directories:
  - venv

install:
 - bash bash/travis_install.sh
  
# command to run tests
script: xvfb-run -a nosetests && cd tests && xvfb-run -a jasmine-ci && cd ../