language: python
sudo: required
python:
  - "2.7"

addons:
  firefox: latest-esr
  apt:
    packages:
    - libyajl1

cache:
  directories:
  - venv
  - superphy/database
  - blast

before_cache:
# - rm -f venv/lib/python2.7/site-packages/superphy

install:
 - python run.py install

# command to run tests
script:
 - source venv/bin/activate
 - nosetests