language: python

python:
  - "2.7"

addons:
  firefox: "41.0"
  apt:
    packages:
    - libyajl1

cache:
  directories:
  - venv
  - db/bigdata-bundled.jar
  - blast

install:
 - bash bash/travis_install.sh

# command to run tests
script:
  - bash bash/test