language: python

python:
  - "2.7"

addons:
  firefox: latest-esr
  apt:
    packages:
    - libyajl1

cache:
  directories:
  - venv
  - db
  - blast

install:
 - bash bash/travis_install.sh

# command to run tests
script:
 - bash bash/test

after-script:
 - rm -f /home/ubiquitin/PycharmProjects/semantic/venv/lib/python2.7/site-packages/superphy